server:
  port: 8989

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Java14SocialMediaFrontEnd
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update